### ISSUE TITLE
Autocomplete in Android Studio not working

### ISSUE THREAD

**Issue by davidbilik** [danger/kotlin#100]
Hi, I'm trying to enable autocompletion and syntax highlighting for kotlin Dangerfiles in AS 4.0+ and I have a trouble in making it work. I think that I've done everything that was in the manual in the README but I still get syntax errors (after multiple restarts) and the error tooltip shows message
```
Cannot access script base class 'systems.danger.kts.DangerFileScript'. Check your module classpath for missing or conflicting dependencies
```
I have installed danger-kotlin 0.5.1 through brew.

Do you know what I might be doing wrong?

**Comment by gianluz** [comment]
Hi, i have a suspect that something wrong with permissions is happening.. have you installed Danger through homebrew? if yes, could you try to uninstall, and install with the script?
```
bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
source ~/.bash_profile
```
then see if works? if yes, then we have something to fix whiles we install with homebrew

**Comment by davidbilik** [comment]
Works 🎉  thx

**Comment by pinguinjkeke** [comment]
Working in IDEA 2020.2, not working in 2022, 2022.1.2
