### ISSUE TITLE
How to get number of additions/deletions on Gitlab Merge request?

### ISSUE THREAD

**Issue by davidbilik** [danger/kotlin#101]
Hi, we use Danger Ruby on our projects hosted on self-hosted GitLab and with ruby we have access to the number of additions/deletions through `git` object in Dangerfile. 

Unfortunately I did not find this option in danger-kotlin. I've found that GitHub provides this and I could access it in `onGitHub` block but it looks like GitLab does not support that. 

So my point is - is it possible to retrieve this number currently? If not, is there any plan to add this to the `git` object? Is it even possible? 

Thanks :)

**Comment by davidbilik** [comment]
I have created a little workaround by reading it through `git` shell command
```
data class GitBoosted(val additions: Int, val deletions: Int)

fun GitLab.gitBoosted(): GitBoosted {
    val diffRefs = mergeRequest.diffRefs
    
    val commandOutput = ProcessBuilder("bash", "-c", "git diff --numstat ${diffRefs.startSha} ${diffRefs.headSha}")
        .redirectOutput(ProcessBuilder.Redirect.PIPE)
        .redirectError(ProcessBuilder.Redirect.PIPE)
        .start().apply { waitFor(60, TimeUnit.MINUTES) }
        .inputStream.bufferedReader().readText()
    
    val pairs = commandOutput.lines()
        .filter { it.isNotEmpty() }
        .map { line ->
            val parts = line.split("\\s+".toRegex())
            parts[0].toInt() to parts[1].toInt()
        }
    val additions = pairs.fold(0) { acc, (addition, _) -> acc + addition }
    val deletions = pairs.fold(0) { acc, (_, deletion) -> acc + deletion }
    return GitBoosted(additions, deletions)
}
```
but it's not ideal of course :)

**Comment by gianluz** [comment]
Interesting workaround, let me to investigate!! if you are lucky i will find a solution shortly

**Comment by davidbilik** [comment]
I have actually find out that danger js has it in their api - https://github.com/danger/danger-js/blob/b615ca41dffa0446c1651300c5d2731ff5988229/source/platforms/git/gitJSONToGitDSL.ts#L158 so maybe it could be easily read?

**Comment by gianluz** [comment]
good shout!! i'm on it!!

**Comment by f-meloni** [comment]
I think with the current infrastructure that is the actual solution.
Danger-Kotlin doesn’t have a gitlab client, then if is the number of added/removed lines is not in the json we get from Danger-js, git looks the best way to get it.

But we added a danger utils exec to execute calls https://github.com/danger/kotlin/pull/98

Then we can release a new version and you can use that one instead, that could help to make the code more readable.

We could also have a function on git to get the added removed lines, but it would have an implementation really similar to the one you wrote.

**Comment by davidbilik** [comment]
@f-meloni I'm probably a little bit lost now :\

Gitlab does not provide this info in their api. But danger-js does. And from my understanding of how danger-kotlin works, it's mainly a wrapper over danger-js. So if danger-js has this, it could be added to the `Git` class introduced in danger-kotlin, right?

Or am I missing something?

**Comment by gianluz** [comment]
yeah that's the problem, we do not have direct access to the api.
Basically what we do is:
- get the JSON from danger js (an example can be found here https://github.com/danger/kotlin/blob/master/danger-kotlin-library/src/test/resources/gitlabDangerJSON.json)
danger js internally has other stuff, to do what you would like to have, we need danger-js to handle that and put everything in that Json. then we can read that.. but i don't know the feasibility right now..

we can keep in mind. but right now, your workaround is not a bad solution.. maybe can just use utils with something like:
```kotlin
data class GitStats(val additions: Int, val deletions: Int)

val GitLab.stats: GitStats
    get() {
        Utils().exec("git diff --numstat ${mergeRequest.diffRefs.startSha} ${mergeRequest.diffRefs.headSha}").let { output ->
            val pairs = output.lines().filter { it.isNotEmpty() }
                .map { line ->
                    val parts = line.split("\\s+".toRegex())
                    parts[0].toInt() to parts[1].toInt()
                }
            val additions = pairs.fold(0) { acc, (addition, _) -> acc + addition }
            val deletions = pairs.fold(0) { acc, (_, deletion) -> acc + deletion }
            return GitStats(additions, deletions)
        }
    }
```

**Comment by f-meloni** [comment]
Danger Kotlin is a not exactly a wrapper over danger-js, they have only one “touch” point, that is the DSL danger-Kotlin receives from danger js (and then Danger Kotlin sends back another json).
Basically danger js handles getting and posting data on the PRs/MRs is not a continuous communication.
Everything else Danger-Kotlin has is built in

**Comment by davidbilik** [comment]
aha! OK guys, now I understand it better :) I am planning to create a plugin with some common stuff that we will use for Merge requests at our company so I can put the extension there and it will be ok :) Thanks again! I love your work and I look forward when I move from danger in ruby to the danger in kotlin since kotlin is my day to day language. So see you soon with another question :D We can close this now I suppose :)

**Comment by gianluz** [comment]
and do not forget to think about us!!! and please feel free to fork our repo, and maybe contribute with interesting stuff!!

**Comment by orta** [comment]
Yeah, just to plus one this general thread as being the way to think about building Danger language implementations 

Danger JS gets the same dumb JSON object as Danger Kotlin and then extends the JSON with it's own APIs - this API in particular is _expensive_ in Danger JS and isn't done by default but it's up to languages to decide whether this should be built-in or not 👍

**Comment by davidbilik** [comment]
Ok so I've tried to extract this to a plugin and I've hit a roadblock right from the beginning because I can't access `GitLab` class in the plugin, looks like it's not provided through `systems.danger:danger-kotlin-sdk:1.1` artifact. I can of course make my method for computing GitStats more abstract without direct dependency to a `GitLab` class but I can imagine that in the future I would like to have access there. What do you suggest?

**Comment by orta** [comment]
Build it into danger-kotlin
