### ISSUE TITLE
Add reports such a ktlint/android lint

### ISSUE THREAD

**Issue by sylwek845** [danger/kotlin#111]
Hi, I was wondering is there's a way to add ktlint style report to add comments?  such as:
``` 
# ktlint
github.dismiss_out_of_range_messages
checkstyle_format.base_path = Dir.pwd
checkstyle_format.report "<project_name>/build/reports/ktlint/ktlint-debug.xml"
```
Thanks

**Comment by gianluz** [comment]
Hi there!!
for android lint i've built a plugin that you can find here : https://github.com/gianluz/danger-kotlin-android-lint-plugin

for ktlint i believe there is nothing at the moment, but nobody stops you to implement your own plugin for ktlint 💯 
is not complicated, you can start using my android lint plugin as starting point!

**Comment by gianluz** [comment]
is not excluded we will add native support for ktlint like Danger Swift that have Swiftlint internally

**Comment by sylwek845** [comment]
OK thanks, create own plugin.
