### ISSUE TITLE
Update to use Kotlin 1.4.0

### ISSUE THREAD

**Issue by uzzu** [danger/kotlin#115]
Hi!

Now danger-kotlin uses Kotlin 1.3.70.
Kotlin 1.3.70 has issue to resolving maven dependencies in kotlin-main-kts, and it had been fixed in Kotlin 1.4.0.
https://youtrack.jetbrains.com/issue/KT-37293

I created danger-kotlin plugin with danger-kotlin-sdk 1.1 and tried to use, but danger-kotlin could not resolve dependencies.
I locally build danger-kotlin and my plugin with Kotlin 1.4.0, then it worked.

It would love to use Kotlin 1.4.0. :)

**Comment by gianluz** [comment]
i've added a follow up PR regarding Kotlin 1.4 Danger Kotlin Script, however we need to check few more things before actually releasing a new version!! will be nice if you can share with me regarding your plugin! you can find me on the kotlin slack!! i would like to know a bit more about your experience and if there is something you would like to improve in the plugin SDK!! cheers mate!

**Comment by uzzu** [comment]
Thanks for the following up!

I have a plan to release the checkstyle report plugin: https://github.com/uzzu/danger-checkstyle-plugin , and I've almost finished to implement features I need.
Now I'm trying to make JUnit report plugin like [danger-junit](https://github.com/orta/danger-junit ).

I thought that requesting a new feature is off topic of this issue. but it might be good to make the danger channel on the kotlin slack to discuss. 👍 

I'm happy to be able to write the danger script with Kotlin, and looking for a new release 😄

**Comment by uzzu** [comment]
@gianluz It looks like the danger-kotlin-sdk with Kotlin 1.4 hasn't been released yet, do you have a plan for it?

**Comment by gianluz** [comment]
i will check if is necessary a new release and let you know soon!!

**Comment by f-meloni** [comment]
Danger-Kotlin 0.7.0 is already out and uses kotlin 1.4 https://github.com/danger/kotlin/blob/master/CHANGELOG.md

**Comment by gianluz** [comment]
this issue was solved! new sdk was released, and kotlin version was upgraded. closing!
