### ISSUE TITLE
Linux init script fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by doodeec** [danger/kotlin#149]
Hello, I've recently updated to Ubuntu 20.04 and whereas the installation script worked before on 18.04 it now fails with
`e: Unable to compile C bridges`

command
```
bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
```
logs
```
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-linux-x86-64.tar.gz (0 bytes/55.1 kiB).
Downloading dependency: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-2-linux-x86-64.tar.gz (55.1 kiB/55.1 kiB). Done.
Extracting dependency: /root/.konan/cache/libffi-3.2.1-2-linux-x86-64.tar.gz into /root/.konan/dependencies
  
Downloading dependency: https://download.jetbrains.com/kotlin/native/lldb-2-linux.tar.gz (0 bytes/30.5 MiB).
Downloading dependency: https://download.jetbrains.com/kotlin/native/lldb-2-linux.tar.gz (30.5 MiB/30.5 MiB). Done.
Extracting dependency: /root/.konan/cache/lldb-2-linux.tar.gz into /root/.konan/dependencies
e: Unable to compile C bridges
  
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':danger-kotlin:linkDebugExecutableRunner'.
> Compilation finished with errors
  
> Task :danger-kotlin:linkDebugExecutableRunner FAILED
  
BUILD FAILED in 41s
2 actionable tasks: 2 executed
make: *** [Makefile:17: build] Error 1
Process exited with code 0
```
Any idea how to fix that or what the problem is?
Thanks

**Comment by f-meloni** [comment]
Hey @doodeec do you have `libncurses5` installed?

Is one of the pre requisites for kolin native on recent Ubuntu https://github.com/JetBrains/kotlin-native#kotlinnative

**Comment by doodeec** [comment]
Hi @f-meloni,
thanks for the suggestion, explicit installation of `libncurses5` helped resolving the issue.
Funny that with Ubuntu 18.04 I didn't have to install that manually :man_shrugging:

**Comment by vchernyshov** [comment]
@doodeec have you faced that kotlinc not found?

**Comment by vchernyshov** [comment]
@doodeec and you didn't have any other issues with running danger kotlin?

**Comment by doodeec** [comment]
@vchernyshov I primarily used it in a project which I'm not working anymore on, but I don't remember any other issue
