### ISSUE TITLE
Bitbucket cloud

### ISSUE THREAD

**Issue by VyshasDojo** [danger/kotlin#180]
Hi, 

We would like to use Danger kotlin and we use bitbucket cloud. Should we follow the same instructions for bitbucket server for bitbucket cloud ?

If not what is the best way to support danger with bitbucket cloud?

**Comment by f-meloni** [comment]
Hi!
Danger Kotlin uses Danger-JS under the hood, so you can set up the environment variables like explained on https://danger.systems/js/usage/bitbucket_cloud.html

**Comment by gianluz** [comment]
this issue seems solved to me! please do not hesitate to let us know if you need any further informations!
