### ISSUE TITLE
Using danger(args) DSL from multiple files changes the current danger instance

### ISSUE THREAD

**Issue by brentwatson** [danger/kotlin#186]
```kotlin
//Dangerfile.df.kts
@file:Import("File1.df.kts", "File2.df.kts")
danger(args) {
    warn("From Root 1")
    test1()
    test2()
    warn("From Root 2")
}

// File1.df.kts
fun test1() = danger(args) {
    warn("From File1")
}

// File2.df.kts
fun test2() = danger(args) {
    warn("From File2")
}
```

Everything ran correctly but what gets added to the PR is missing first 2 warnings:
> "From File2"
> "From Root 2"

I was expecting this to act  something like:

```kotlin
danger(args) {
    warn("From Root 1")
    warn("From File1")
    warn("From File2")
    warn("From Root 2")
}
```

I spoke with @f-meloni about this who found that calling
> ```kotlin
> inline fun danger(args: Array<String>, block: DangerDSL.() -> Unit) = Danger(args).run(block)
> ```
> changes the current danger instance (which should never happen), and that means that the "messages" list is re created.

**Comment by f-meloni** [comment]
Hi @brentwatson, thank you very much.
I've opened https://github.com/danger/kotlin/pull/185 which should solve the issue
