### ISSUE TITLE
Failed to install current version 0.7.1 on macOs

### ISSUE THREAD

**Issue by afaucogney** [danger/kotlin#190]
I succeed a couple of month ago to install the 0.7.0 to test Danger in my Gitlab CI
Today, when I restart the build, brew retrieve the 0.7.1 that failed !  https://github.com/danger/homebrew-tap/issues/9 

Any help would be welcome.
Is there any way I can install the latest OR specific version from my CI ?

**Comment by gianluz** [comment]
Yes homebrew needs to be fixed, but you can try using the installation script for Linux. You can find the command to run in the README.md

**Comment by afaucogney** [comment]
Migrate to 1.0.0. So I close the issue !
