### ISSUE TITLE
How to use the `gem install danger-auto_label` 

### ISSUE THREAD

**Issue by anticafe** [danger/kotlin#204]
I know it's possible if use the original Danger (Ruby) version, then call `gem install danger-auto_label` to install `auto_label` plugin.

But, if use the Danger-Kotlin docker image (`ghcr.io/danger/danger-kotlin:1.0.0`), how to install such plugin? Or I must use the Danger Ruby instead?

**Comment by anticafe** [comment]
Hi @f-meloni Can you help? 🙇

**Comment by f-meloni** [comment]
Hi @anticafe, Danger-Kotlin is not compatible with Danger Ruby and its plugins, so I don't think it will work, however Danger has the possibility to execute command line commands, so if you want to add a label to something on GitHub you can probably use Danger Kotlin to execute the GitHub CLI.

**Comment by anticafe** [comment]
Thanks @f-meloni . Do you have any link or keyword so that I can learn how to execute Github CLI via Danger Kotlin?

**Comment by f-meloni** [comment]
Hey! Sorry for the delay, I've missed this, you can use https://github.com/danger/kotlin/blob/master/danger-kotlin-library/src/main/kotlin/systems/danger/kotlin/models/danger/Utils.kt#L24 to exec any shell command

**Comment by gianluz** [comment]
Closing as seems solved! 😄
