### ISSUE TITLE
Run on custom inhouse CI

### ISSUE THREAD

**Issue by k0shk0sh** [danger/kotlin#209]
Can we somehow run `danger-kotlin ci` on a custom in-house ci? my ios colleagues uses danger and they could hack it by exporting an env variable `export TEAMCITY_VERSION="dummy";` however with danger-kotlin it doesn't work and I get this error below: 

```
Executing $(which danger) ci --process danger-kotlin --passURLForDSL  - pid 3556
Skipping Danger due to this run not executing on a PR.
Step finished successfully.

**Comment by k0shk0sh** [comment]
Nvm, I got it working finally!

**Comment by sp0rk** [comment]
> Nvm, I got it working finally!

Why wouldn't you share your solution then?

**Comment by k0shk0sh** [comment]
> > Nvm, I got it working finally!
> 
> Why wouldn't you share your solution then?

I just copied their install.sh into the custom CI.
