### ISSUE TITLE
Could not find a DangerFile

### ISSUE THREAD

**Issue by BekaChachua** [danger/kotlin#232]
After running command ```bundle exec danger``` i get an error 
**[!] Could not find a Dangerfile.**

Whole process looks like this:
* ```gem install bundler```
* ```bundler init```
* Gemfile
    ```
    # frozen_string_literal: true
    source "https://rubygems.org"
    
    git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
    
    # gem "rails"
    gem 'danger'
    ```
* ```bundle install```
  ```bundle exec danger --version```
* ```bundle exec danger init```
***
CI/CD side 
* ```bundle install```
* ```bundle exec danger```

Does anyone know how to solve this problem?

**Comment by orta** [comment]
You might want to start adding some debugging logs in the danger source code - that shouldn't happen (assuming there is a `Dangerfile` in that working dir)

**Comment by f-meloni** [comment]
This seems to be using Danger Ruby, not Danger Kotlin

**Comment by gianluz** [comment]
Closing as this is something related to danger ruby and not danger kotlin
