### ISSUE TITLE
Add label on a PR

### ISSUE THREAD

**Issue by igor-budi** [danger/kotlin#239]
For the ruby counterpart, there are options to add labels to a PR from the DangerFile.
Is this something that you are considering and can be added to the API surface of this library?
Are there any other, external, options that can be used?

**Comment by gianluz** [comment]
Hi Igor! Thanks for the issue, there is an open discussion if we should make he github api part of danger kotlin by default, but this can be something someone else using Gitlab or Bitbucket don't need. Danger kotlin supports every maven dependency and you can import in your danger file easily through the annotations `DependsOn`, or a custom Plugin for danger kotlin can be implemented. 

If you can find a library for java or kotlin that does that already you can try import that and use it, or you could open-source a new plugin! i'd be happy to offer guidance

**Comment by gianluz** [comment]
@igor-budi i've successfully added labels and modified merge request with gitlab4j imported directly within the danger file

**Comment by gianluz** [comment]
i think this can be easily achieved for github with (https://mvnrepository.com/artifact/org.kohsuke/github-api) and bitbucket with https://developer.atlassian.com/server/bitbucket/reference/java-api/
