### ISSUE TITLE
Docs about Environment Dependencies

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [danger/kotlin#273]
Hey, I just tried this in Docker using the Linux install script, and got surprised twice already. It looks like this tool depends on both NPM and a JDK, but I couldn't find anything mentioning this in the README or any other docs. Would you mind adding some docs saying which tools are expected and which versions are supported?

Cheers

**Comment by Vacxe** [comment]
Could you please describe your problem more detailed please?

Why did you used "Linux install script" in "Docker"? 

1. We providing [docker image](https://github.com/danger/kotlin/pkgs/container/danger-kotlin) as well 
2. If you doing your own Docker image you can depend if from 1. or take a look on [docker file](https://github.com/danger/kotlin/blob/master/Dockerfile)
3. Danger Kotlin is actually a "Bridge" for Danger JS, so, Danger JS required `node`, Kotlin is JVM type language. what required `JDK`.
4. Using Linux Install Script is prefer if you want to install Danger Kotlin + Env Dependencies on host machine (like using `brew` on Mac), but for "In Docker" I'll recommend to take a look on the other solutions or 2.

Let me know if you have any questions

**Comment by hubertgrzeskowiak** [comment]
Oh damn! I didn't realise there were Docker images ready! Cheers. Yeah, I overlooked it and tried to build my own

**Comment by Vacxe** [comment]
@hubertgrzeskowiak can you close this issue as well if problem is resolved, cheers
