### ISSUE TITLE
[BUG] Linux installation fails on Kotlin download

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [danger/kotlin#274]
Looks like the Kotlin native package is no longer available under the hardcoded URL.

Step to reproduce:
```
bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
```
Running on Amazon Linux image `amazoncorretto:11` and after installing the most common dependencies (tar, gzip, unzip, make, git, nvm, node etc.)

```
Build file '/root/_danger-kotlin/danger-kotlin/build.gradle.kts' line: 22

* What went wrong:
Could not resolve all files for configuration ':danger-kotlin:detachedConfiguration1'.
> Could not find :kotlin-native-prebuilt-linux-aarch64:1.7.0.
  Searched in the following locations:
    - https://download.jetbrains.com/kotlin/native/builds/releases/1.7.0/linux-aarch64/kotlin-native-prebuilt-linux-aarch64-1.7.0.tar.gz
  Required by:
      project :danger-kotlin
```

**Comment by hubertgrzeskowiak** [comment]
I found the newest 1.7 release at https://github.com/JetBrains/kotlin/releases/tag/v1.7.22

**Comment by Vacxe** [comment]
@hanneskaeufler  wanna create PR mate or wish me do it?

**Comment by Vacxe** [comment]
As well, it always good to attach the steps to repeat this bug. That`s a linux installation script or something else?

**Comment by hubertgrzeskowiak** [comment]
My bad. Edited the original report now.

**Comment by hubertgrzeskowiak** [comment]
Thanks a lot!
