### ISSUE TITLE
MissingFieldException

### ISSUE THREAD

**Issue by fdcibernie** [danger/kotlin#277]
Dangerfile.df.kts /tmp/danger-dsl-ba8cd85d.json danger_out.json - pid 36
kotlinx.serialization.MissingFieldException: Fields [id, login, type, avatar_url] are required for type with serial name 'systems.danger.kotlin.models.github.GitHubUser', but they were missing

<img width="1018" alt="error danger run" src="https://github.com/danger/kotlin/assets/162972942/18f44563-e058-4497-a294-83c4b2f415d0">

**Comment by Vacxe** [comment]
> Thanks for reporting, will take a look ASAP

**Comment by fdcibernie** [comment]
Hi @Vacxe
Any update on this? thanks

**Comment by Vacxe** [comment]
@fdcibernie just in time when I work on it ;)

**Comment by fdcibernie** [comment]
@Vacxe I got this new error
<img width="1016" alt="Screenshot 2024-04-24 at 1 18 23 PM" src="https://github.com/danger/kotlin/assets/162972942/9c9a6f3b-4aec-407b-8e0b-58486ee378a4">

**Comment by Vacxe** [comment]
@fdcibernie could you try to rerun it? I rebuild container with old version of Danger JS

**Comment by Vacxe** [comment]
@orta probably some issue with Danger JS

**Comment by fdcibernie** [comment]
**@Vacxe**  the error perviously was appear. 

> kotlinx.serialization.MissingFieldException: Fields [id, login, type, avatar_url] are required for type with serial name 'systems.danger.kotlin.models.github.GitHubUser', but they were missing

**Comment by Vacxe** [comment]
@fdcibernie please re-run again. Serialization should be fixed now. Please let me know if everything is ok.

**Comment by fdcibernie** [comment]
@Vacxe kotlinx.serialization.MissingFieldException: Field 'avatar_url' is required for type with serial name 'systems.danger.kotlin.models.github.GitHubUser', but it was missing

**Comment by Vacxe** [comment]
@fdcibernie oh, I'm blinded. Don't know how I missed it. Will fix the release asap once back home. Sorry for the delay.

**Comment by Vacxe** [comment]
@fdcibernie done from mobile :) should work now please check

**Comment by fdcibernie** [comment]
Thanks **@Vacxe** issue resolved.

**Comment by Vacxe** [comment]
@fbartho please take a look on `gitbeaker` issue. Installed via npm in docker
