### ISSUE TITLE
github action doesn't work

### ISSUE THREAD

**Issue by pinkasey** [danger/kotlin#94]
This is my action:
(I believe only the last part is relevant, from `name: Danger`)
```
jobs:
  detekt_job:
    runs-on: ubuntu-latest
    name: GitHub Action for Maven
    steps:
      - uses: actions/checkout@v1
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          ENVIRONMENT: 'dev'
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Diffset
        id: diffset
        uses: softprops/diffset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mvn install -pl DetektExtensions
          mvn detekt:check
      - name: Danger
        uses: danger/kotlin@master
        with:
          args: "--id DangerKotlinAction"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I get the following error:

```
com.squareup.moshi.JsonDataException: Required value 'issue' missing at $.danger.github
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:96)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
	at systems.danger.kotlin.DangerRunner.<init>(DangerRunner.kt:125)
	at systems.danger.kotlin.DangerRunnerKt.Danger(DangerRunner.kt:238)
	at Dangerfile_df.<init>(Dangerfile.df.kts:14)
Uncaught Kotlin exception: kotlin.Exception: Command kotlinc -script-templates systems.danger.kts.DangerFileScript -cp /usr/local/lib/danger/danger-kotlin.jar -script Dangerfile.df.kts /tmp/danger-dsl.json danger_out.json exited with code 768

        at kfun:systems.danger.cmd.Cmd.exec() (0x21c739)
        at kfun:systems.danger.cmd.dangerfile.DangerFile.execute(kotlin.String;kotlin.String) (0x21d227)
        at kfun:systems.danger.DangerKotlin.run() (0x21c0e6)
        at Init_and_run_start (0x21f472)
        at __libc_start_main (0x7f42070f6b97)

        at  (0x20f029)
        at  ((nil))
```

My Danger file:
```
import org.w3c.dom.Document
import org.w3c.dom.Element
import systems.danger.kotlin.Danger
import systems.danger.kotlin.warn
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory

val danger = Danger(args)
```

I've tried `danger/kotlin@master`, and I've tried `danger/kotlin@0.5.1` - same error

**Comment by gianluz** [comment]
https://github.com/danger/kotlin/pull/95 should solve, could you try from danger/kotlin@github-issue-optional please?

**Comment by pinkasey** [comment]
Thanks!
I'll try it and let you know
(Probably on Sunday)

**Comment by f-meloni** [comment]
We don't have `issue` optional on danger-swift. https://github.com/danger/swift/blob/master/Sources/Danger/GitHubDSL.swift#L17
Danger-Swift is been around for a while now and we never hit a problem like that, I'm then curious to know why.
@pinkasey Is is possible (unless it is private), to share the PR where this is happening?

**Comment by pinkasey** [comment]
It's a private repo from my work-place.
What does `issue` represent? an issue in github?
if so, that explains it -
We don't work with github-issues in my company.
We work with Jira.

**Comment by f-meloni** [comment]
AFAIK PR is always also an issue, if you try to get an issue (https://developer.github.com/v3/issues/#get-an-issue) using a PR number it will show you the issue data for that PR.
Take for example the PR @gianluz just opened https://api.github.com/repos/danger/kotlin/issues/95 this is the issue data related to that PR. 
I don't understand why it is missing in your case.

**Comment by pinkasey** [comment]
What you say makes sense.
If only there was more info in the output, we could understand better what's going on...

I've tried `println("args: $args")`,
but that only gave me something like
`args: [Ljava.lang.String;@50406145`

**Comment by pinkasey** [comment]
I've ran it with 

now I get this error:
```
com.squareup.moshi.JsonDataException: Required value 'pullRequest' missing at $.danger.github
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:96)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:83)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
	at systems.danger.kotlin.DangerRunner.<init>(DangerRunner.kt:125)
	at systems.danger.kotlin.DangerRunnerKt.Danger(DangerRunner.kt:238)
	at Dangerfile_df.<init>(Dangerfile.df.kts:14)
Uncaught Kotlin exception: kotlin.Exception: Command kotlinc -script-templates systems.danger.kts.DangerFileScript -cp /usr/local/lib/danger/danger-kotlin.jar -script Dangerfile.df.kts /tmp/danger-dsl.json danger_out.json exited with code 768
```

Obviously, it's not about the `issue` -
the content of `/tmp/danger-dsl.json` is completely wrong. I'm guessing it's completely empty.

I'll try to output it's content to console and post it here.

I think a take-away from this thread, is that if deserializing the input json fails - better print a more verbose error message, something like

> "something is wrong with the input-file for Danger (/tmp/danger-dsl.json), which is calculated in a previous step (which?). here's the error: "...missing issue...", here's the file content: ..."

**Comment by gianluz** [comment]
May i ask how you are triggering the job?? is against a pull request? i'm suspecting is failing because there is not pull request here..

**Comment by pinkasey** [comment]
yes, on a pull-request:
```
name: danger-detekt

on:
  push:
    branches: [ my_branch ]
  pull_request:
    branches: [ my_branch ]
```

**Comment by gianluz** [comment]
could you try only on pull-request and remove temporarily on push? because danger is made to work on pull requests only.. should check your code before merging something, in a pull-request, not when you push a branch..

**Comment by f-meloni** [comment]
Also I wonder if is related to this https://github.com/danger/danger-js/issues/1042

**Comment by pinkasey** [comment]
I'm trying both -
removed 'push' and added `DANGER_GITHUB_API_BASE_URL `

For now, it seems like github doesn't think he needs to run the action at all:
![Uploading image.png…]()
It's been like that for ~10 minutes.
I'll update if it makes progress..

If you guys can point me to an example repo where danger/kotlin does work - that might also help.

**Comment by pinkasey** [comment]
OK
I've changed my main.yml (workflow file) to the one in this repo (`danger.yml`) - now it seems to run successfully.
I'll work my way from here.

Thanks for the replies.
I still suggest a more helpful error-message in the case that I've encounter, I'll try to open a PR.

**Comment by mokagio** [comment]
>  I'll try to open a PR
Thanks ✨ 👍

**Comment by gianluz** [comment]
Looks like this issue was solved! closing
